litellm_settings:
  store_audit_logs: true
  callbacks: ["arize_phoenix", "prometheus"]
  service_callback: ["prometheus"]

# self hosted
model_list:
  - model_name: glm-4.7-flash
    litellm_params:
      model: ollama/glm-4.7-flash
      api_base: os.environ/GLM_BASE_URL

  - model_name: deepseek-v3.2
    litellm_params:
      model: ollama/deepseek-v3.2
      api_base: os.environ/DEEPSEEK_BASE_URL

  - model_name: vllm-deepseek
    litellm_params:
      model: hosted_vllm/deepseek-ai/DeepSeek-R1
      api_base: http://vllm.ai-lab.svc.cluster.local:8000

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  
  proxy_batch_write_at: 60
  database_connection_pool_limit: 10

  key_management_system: "hashicorp_vault"
  key_management_settings: 
    store_virtual_keys: true # OPTIONAL. Defaults to False, when True will store virtual keys in secret manager
    prefix_for_stored_virtual_keys: "litellm/" # OPTIONAL. If set, this prefix will be used for stored virtual keys in the secret manager
    access_mode: "read_and_write"